apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector: # Pod selector label
    matchLabels:
      app: mysql
  strategy: # Strategy for our Deployment
    type: Recreate 
  template: # Pod template
    metadata: 
      labels: 
        app: mysql
    spec: # Pod Specification
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql    
          volumeMounts: # Container level resource
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: # Pod Spec level resource
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-pvc # referenced name on PVC manifest
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script # referenced name on ConfigMap manifest